// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-aWG9s9UOl7n5MwsdUYUQE9ikRQrCSA',
    appId: '1:994530050638:web:f376bf4a92c4189fe7391f',
    messagingSenderId: '994530050638',
    projectId: 'chat-gpt-9ee62',
    authDomain: 'chat-gpt-9ee62.firebaseapp.com',
    storageBucket: 'chat-gpt-9ee62.appspot.com',
    measurementId: 'G-5PKNLL5NVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGUrrjNm0lDLiFfeR41aJno8NA85IBSiI',
    appId: '1:994530050638:android:8aaa72a65ed10148e7391f',
    messagingSenderId: '994530050638',
    projectId: 'chat-gpt-9ee62',
    storageBucket: 'chat-gpt-9ee62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFCz46f-SRjMB9PcEOd1piTKu1m9HKBVA',
    appId: '1:994530050638:ios:5c89c7487abcf9cde7391f',
    messagingSenderId: '994530050638',
    projectId: 'chat-gpt-9ee62',
    storageBucket: 'chat-gpt-9ee62.appspot.com',
    iosBundleId: 'com.example.chatGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFCz46f-SRjMB9PcEOd1piTKu1m9HKBVA',
    appId: '1:994530050638:ios:65caaaca61da6d36e7391f',
    messagingSenderId: '994530050638',
    projectId: 'chat-gpt-9ee62',
    storageBucket: 'chat-gpt-9ee62.appspot.com',
    iosBundleId: 'com.example.chatGpt.RunnerTests',
  );
}
